### ISSUE TITLE
Mathjax flashes unrendered

### ISSUE THREAD

**Issue by csmith** [mdbot/wiki#52]
When you're refreshing a page with mathjax it flashes up as nonsense then gets replaced.

Using `$$` blocks the output is centered so it also ends up jumping from the left to the center of the content.

I wonder if we can hide it until Mathjax is loaded and rendered, or something?

**Comment by greboid** [comment]
This was fixed in b9ed2181d175280ee90df2da098165c8d2ccb3eb
